"""add_all_core_tables

Revision ID: 59919a6d4848
Revises:
Create Date: 2026-03-23 08:09:54.227402

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

try:
    import pgvector.sqlalchemy  # noqa: F401  # available on PostgreSQL envs
except ImportError:
    pgvector = None  # type: ignore[assignment]


# revision identifiers, used by Alembic.
revision: str = "59919a6d4848"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("primary_provider", sa.String(length=50), nullable=False),
        sa.Column("primary_action", sa.String(length=10), nullable=False),
        sa.Column("primary_confidence", sa.Integer(), nullable=False),
        sa.Column("secondary_provider", sa.String(length=50), nullable=True),
        sa.Column("secondary_action", sa.String(length=10), nullable=True),
        sa.Column("secondary_confidence", sa.Integer(), nullable=True),
        sa.Column("agreed", sa.Boolean(), nullable=False),
        sa.Column("rag_context_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_decisions_action"), "ai_decisions", ["action"], unique=False)
    op.create_index(
        op.f("ix_ai_decisions_created_at"), "ai_decisions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_ai_decisions_user_id"), "ai_decisions", ["user_id"], unique=False)
    op.create_table(
        "fee_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("management_fee_rate", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("performance_fee_rate", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("high_water_mark_enabled", sa.Boolean(), nullable=False),
        sa.Column("minimum_aum", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_sources_status"), "knowledge_sources", ["status"], unique=False
    )
    op.create_table(
        "portfolio_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open_value_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("close_value_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("high_value_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("low_value_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("pnl_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("pnl_pct", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("avg_health_factor", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("snapshot_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_history_period_start"),
        "portfolio_history",
        ["period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_history_period_type"), "portfolio_history", ["period_type"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_history_user_id"), "portfolio_history", ["user_id"], unique=False
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("total_value_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("total_supply_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("total_borrow_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("health_factor", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("positions_json", sa.JSON(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_recorded_at"),
        "portfolio_snapshots",
        ["recorded_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_user_id"), "portfolio_snapshots", ["user_id"], unique=False
    )
    op.create_table(
        "proposals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("ai_decision_id", sa.Integer(), nullable=True),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("expected_hf_after", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("estimated_gas_usd", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tx_hash", sa.String(length=100), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_proposals_created_at"), "proposals", ["created_at"], unique=False)
    op.create_index(op.f("ix_proposals_status"), "proposals", ["status"], unique=False)
    op.create_index(op.f("ix_proposals_user_id"), "proposals", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("wallet_address", sa.String(length=100), nullable=True),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("tx_hash", sa.String(length=100), nullable=True),
        sa.Column("chain", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("ai_decision_id", sa.Integer(), nullable=True),
        sa.Column("gas_used", sa.Numeric(precision=20, scale=0), nullable=True),
        sa.Column("gas_price_gwei", sa.Numeric(precision=20, scale=9), nullable=True),
        sa.Column("is_dry_run", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_asset"), "transactions", ["asset"], unique=False)
    op.create_index(
        op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_transactions_operation"), "transactions", ["operation"], unique=False)
    op.create_index(op.f("ix_transactions_status"), "transactions", ["status"], unique=False)
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_version", sa.String(length=20), nullable=True),
        sa.Column("risk_mode", sa.String(length=20), nullable=True),
        sa.Column("notification_email", sa.String(length=255), nullable=True),
        sa.Column("notification_frequency", sa.String(length=20), nullable=False),
        sa.Column("max_single_trade_usd", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("max_daily_trade_usd", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "fee_calculations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("calculation_date", sa.Date(), nullable=False),
        sa.Column("period_type", sa.String(length=10), nullable=False),
        sa.Column("aum_snapshot", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("management_fee", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("performance_fee", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("total_fee", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("profit_since_hwm", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("high_water_mark", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fee_calculations_user_id"), "fee_calculations", ["user_id"], unique=False
    )
    op.create_table(
        "high_water_marks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("hwm_value", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_high_water_marks_user_id"), "high_water_marks", ["user_id"], unique=True
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["knowledge_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notification_email", sa.String(length=255), nullable=True),
        sa.Column("notification_frequency", sa.String(length=20), nullable=False),
        sa.Column("max_single_trade_usd", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("max_daily_trade_usd", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("risk_mode", sa.String(length=20), nullable=False),
        sa.Column("dark_mode", sa.Boolean(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=False),
        sa.Column("two_factor_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=True)
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1536) if pgvector else sa.Text(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["knowledge_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("knowledge_chunks")
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.drop_table("user_settings")
    op.drop_table("knowledge_documents")
    op.drop_index(op.f("ix_high_water_marks_user_id"), table_name="high_water_marks")
    op.drop_table("high_water_marks")
    op.drop_index(op.f("ix_fee_calculations_user_id"), table_name="fee_calculations")
    op.drop_table("fee_calculations")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_operation"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_asset"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_proposals_user_id"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_status"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_created_at"), table_name="proposals")
    op.drop_table("proposals")
    op.drop_index(op.f("ix_portfolio_snapshots_user_id"), table_name="portfolio_snapshots")
    op.drop_index(op.f("ix_portfolio_snapshots_recorded_at"), table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index(op.f("ix_portfolio_history_user_id"), table_name="portfolio_history")
    op.drop_index(op.f("ix_portfolio_history_period_type"), table_name="portfolio_history")
    op.drop_index(op.f("ix_portfolio_history_period_start"), table_name="portfolio_history")
    op.drop_table("portfolio_history")
    op.drop_index(op.f("ix_knowledge_sources_status"), table_name="knowledge_sources")
    op.drop_table("knowledge_sources")
    op.drop_table("fee_configs")
    op.drop_index(op.f("ix_ai_decisions_user_id"), table_name="ai_decisions")
    op.drop_index(op.f("ix_ai_decisions_created_at"), table_name="ai_decisions")
    op.drop_index(op.f("ix_ai_decisions_action"), table_name="ai_decisions")
    op.drop_table("ai_decisions")
    # ### end Alembic commands ###
