#!/bin/bash
set -euo pipefail

# ───────────────────────────────────────────────
# -v / --volumes フラグ誤使用防止ガード
# docker compose down -v はDBボリュームを削除してテスターデータが全滅する
# ───────────────────────────────────────────────
for _arg in "$@"; do
  if [[ "$_arg" == "-v" || "$_arg" == "--volumes" ]]; then
    echo "❌ ERROR: -v / --volumes フラグは禁止です。DBボリュームが削除されテスターデータが全て消えます。"
    echo "   down のみ使用してください: docker compose ... down"
    exit 1
  fi
done

# Ultra AutoTrade – production ワンショットデプロイスクリプト
# (2026-04-17 B案リネーム: 旧 deploy_staging.sh → deploy_production.sh)
# (2026-04-27 ゼロダウンタイム対応: --backend-only は Blue/Green 切替に変更)
#
# 使い方:
#   ./scripts/deploy_production.sh                  # フルデプロイ (初期 active=blue)
#   ./scripts/deploy_production.sh --frontend-only  # フロントエンドのみ
#   ./scripts/deploy_production.sh --backend-only   # Blue/Green 切替 (ゼロダウンタイム)
#   ./scripts/deploy_production.sh --no-build       # ビルドなし（up -d のみ）
#   ./scripts/deploy_production.sh --help

# ───────────────────────────────────────────────
# 定数
# ───────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
COMPOSE_FILE="docker-compose.production.yml"
ENV_FILE=".env.production"
# 2026-04-24 container_name 衝突インシデント後、*-production suffix に統一
FRONTEND_CONTAINER="ultra-autotrade-frontend-production"
BACKEND_BLUE_CONTAINER="ultra-autotrade-backend-blue-production"
BACKEND_GREEN_CONTAINER="ultra-autotrade-backend-green-production"
NGINX_CONTAINER="ultra-autotrade-nginx-production"
POSTGRES_CONTAINER="ultra-autotrade-postgres-production"
CLOUDFLARED_CONTAINER="ultra-autotrade-cloudflared-production"
HEALTH_TIMEOUT=60

# Blue/Green host-side ports (compose の定義と一致させること)
BLUE_PORT=8010
GREEN_PORT=8011
NGINX_PORT=8080

UPSTREAM_CONF="${PROJECT_ROOT}/docker/nginx/upstream.conf"
LOCK_FILE="${PROJECT_ROOT}/.deploy-production.lock"

# ───────────────────────────────────────────────
# ヘルパー
# ───────────────────────────────────────────────
log()  { echo "[deploy] $*"; }
err()  { echo "[deploy] ERROR: $*" >&2; }

slack_notify() {
  local msg="$1"
  if [[ -n "${SLACK_WEBHOOK_URL:-}" ]]; then
    curl -s -X POST "${SLACK_WEBHOOK_URL}" \
      -H "Content-Type: application/json" \
      -d "{\"text\": \"${msg}\"}" >/dev/null || true
  fi
}

show_help() {
  cat <<'EOF'
deploy_production.sh — Ultra AutoTrade production デプロイ

使い方:
  ./scripts/deploy_production.sh [OPTIONS]

オプション:
  --frontend-only   フロントエンドのみリビルド＆再起動
  --backend-only    Blue/Green 切替によるゼロダウンタイムデプロイ
  --no-build        ビルドなしで up -d のみ実行
  --help            このヘルプを表示

注意:
  - /opt/ultra-autotrade（または git root）から実行すること
  - .env.production が同ディレクトリに存在していること
  - Blue/Green 切替には docker/nginx/upstream.conf と nginx コンテナが必要
EOF
  exit 0
}

# docker compose / docker-compose の解決
resolve_dc() {
  if docker compose version >/dev/null 2>&1; then
    echo "docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    echo "docker-compose"
  else
    err "docker compose または docker-compose が見つかりません"
    exit 1
  fi
}

# ヘルスチェック待ちループ
wait_healthy() {
  local url="$1"
  local label="$2"
  local deadline=$(( $(date +%s) + HEALTH_TIMEOUT ))

  log "ヘルスチェック待ち: ${label} (最大 ${HEALTH_TIMEOUT}s)"
  while true; do
    if curl -sf --max-time 3 "${url}" >/dev/null 2>&1; then
      log "${label} OK"
      return 0
    fi
    if [[ $(date +%s) -ge ${deadline} ]]; then
      err "${label} がタイムアウトしました (${url})"
      return 1
    fi
    sleep 3
  done
}

# ───────────────────────────────────────────────
# Blue/Green ヘルパー
# ───────────────────────────────────────────────

# upstream.conf から active slot を判定
read_active_slot() {
  if [[ ! -f "${UPSTREAM_CONF}" ]]; then
    echo "unknown"
    return
  fi
  if grep -qE '^[[:space:]]*server[[:space:]]+backend-blue:' "${UPSTREAM_CONF}"; then
    echo "blue"
  elif grep -qE '^[[:space:]]*server[[:space:]]+backend-green:' "${UPSTREAM_CONF}"; then
    echo "green"
  else
    echo "unknown"
  fi
}

# upstream.conf を書き換え (awk + 一時ファイル + mv、sed -i は禁止)
write_upstream_conf() {
  local new_slot="$1"  # blue or green
  local tmp_file
  tmp_file=$(mktemp "${UPSTREAM_CONF}.XXXXXX")
  awk -v slot="${new_slot}" -v ts="$(date -Iseconds 2>/dev/null || date +%Y-%m-%dT%H:%M:%S)" '
    BEGIN {
      printf "# Auto-generated by deploy_production.sh at %s\n", ts
      printf "# Active slot: %s\n", slot
      printf "server backend-%s:8000 max_fails=3 fail_timeout=10s;\n", slot
    }
  ' </dev/null > "${tmp_file}"
  mv "${tmp_file}" "${UPSTREAM_CONF}"
}

# 現在 active な backend コンテナ名を返す (DB drift / 401 チェック用)
active_backend_container() {
  local slot
  slot=$(read_active_slot)
  if [[ "${slot}" = "green" ]]; then
    echo "${BACKEND_GREEN_CONTAINER}"
  else
    echo "${BACKEND_BLUE_CONTAINER}"
  fi
}

# Blue/Green ゼロダウンタイム切替
deploy_backend_zero_downtime() {
  local active_slot inactive_slot inactive_port
  active_slot=$(read_active_slot)

  if [[ "${active_slot}" = "blue" ]]; then
    inactive_slot="green"; inactive_port="${GREEN_PORT}"
  elif [[ "${active_slot}" = "green" ]]; then
    inactive_slot="blue";  inactive_port="${BLUE_PORT}"
  else
    err "upstream.conf から active slot を判定できません: ${UPSTREAM_CONF}"
    err "復旧: 手動で upstream.conf に 'server backend-blue:8000 max_fails=3 fail_timeout=10s;' を書き、nginx を起動してください"
    return 1
  fi

  log "Blue/Green 切替開始: active=${active_slot} → new=${inactive_slot}(:${inactive_port})"

  # 1. 新コンテナをビルド (旧コンテナは稼働継続)
  if ! "${NO_BUILD}"; then
    log "backend-${inactive_slot} をビルド中..."
    ${DC} -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" build "backend-${inactive_slot}"
  fi

  # 2. 新コンテナを起動 (--no-deps で他サービスに影響を与えない)
  log "backend-${inactive_slot} を起動..."
  ${DC} -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d --no-deps "backend-${inactive_slot}"

  # 3. 新コンテナのヘルスチェック (ホスト側ポート直打ち)
  if ! wait_healthy "http://127.0.0.1:${inactive_port}/health" "backend-${inactive_slot}"; then
    err "新コンテナのヘルスチェック失敗。切替を中止し新コンテナを停止します"
    ${DC} -f "${COMPOSE_FILE}" stop "backend-${inactive_slot}" 2>/dev/null || true
    return 1
  fi

  # 4. nginx upstream を切替 (awk + 一時ファイル + mv)
  log "upstream.conf を ${inactive_slot} に書き換え..."
  write_upstream_conf "${inactive_slot}"

  # 5. nginx -s reload (POSIX 仕様で既存接続を引き継ぐ → ゼロダウンタイム保証)
  log "nginx -s reload を実行..."
  if ! docker exec "${NGINX_CONTAINER}" nginx -s reload; then
    err "nginx reload 失敗。upstream.conf を ${active_slot} に戻して再 reload..."
    write_upstream_conf "${active_slot}"
    docker exec "${NGINX_CONTAINER}" nginx -s reload || true
    return 1
  fi
  log "✅ nginx upstream → backend-${inactive_slot} 切替完了"

  # 6. 30秒待機 (既存接続の収束)
  log "30秒待機して既存接続が収束するのを待つ..."
  sleep 30

  # 7. 旧コンテナを stop (rm はしない、緊急ロールバックに備えて停止状態で残す)
  log "backend-${active_slot} を stop (緊急ロールバック用に rm はしない)..."
  ${DC} -f "${COMPOSE_FILE}" stop "backend-${active_slot}"

  log "✅ Blue/Green 切替完了: active=${inactive_slot}"
  log "   ロールバック手順: docker/nginx/upstream.conf を 'server backend-${active_slot}:8000 ...' に書き戻し、"
  log "                  ${DC} -f ${COMPOSE_FILE} start backend-${active_slot} → docker exec ${NGINX_CONTAINER} nginx -s reload"
  return 0
}

# ───────────────────────────────────────────────
# 引数パース
# ───────────────────────────────────────────────
FRONTEND_ONLY=false
BACKEND_ONLY=false
NO_BUILD=false

for arg in "$@"; do
  case "${arg}" in
    --frontend-only) FRONTEND_ONLY=true ;;
    --backend-only)  BACKEND_ONLY=true ;;
    --no-build)      NO_BUILD=true ;;
    --help)          show_help ;;
    *) err "不明なオプション: ${arg}"; exit 1 ;;
  esac
done

# ───────────────────────────────────────────────
# 前提チェック
# ───────────────────────────────────────────────
cd "${PROJECT_ROOT}"
log "project root: ${PROJECT_ROOT}"

if [[ ! -f "${COMPOSE_FILE}" ]]; then
  err "${COMPOSE_FILE} が見つかりません（${PROJECT_ROOT}）"
  exit 1
fi

if [[ ! -f "${ENV_FILE}" ]]; then
  err "${ENV_FILE} が見つかりません — デプロイを中止します"
  exit 1
fi

if [[ ! -f "${UPSTREAM_CONF}" ]]; then
  err "${UPSTREAM_CONF} が見つかりません — Blue/Green 構成が壊れている可能性"
  err "復旧: docker/nginx/upstream.conf を 'server backend-blue:8000 max_fails=3 fail_timeout=10s;' で作成してください"
  exit 1
fi

# === デプロイの同時実行排除 (flock) ===
exec 200>"${LOCK_FILE}"
if ! flock -n 200; then
  err "別のデプロイが進行中です: ${LOCK_FILE}"
  err "進行中のデプロイが終わるか、ロックが古い場合は手動で削除してから再実行してください"
  exit 1
fi

# === Production deploy guardrails (2026-04-19 根本解決原則) ===
# .env.production が本番固有の値を持っていることを保証する予防層。
# 2026-04-18 sed 一斉更新インシデント再発防止。

# Guard 1: .env.production 必須キー検証
if ! grep -q '^APP_ENV=production$' .env.production; then
  echo "❌ FAIL: .env.production に APP_ENV=production がない"
  exit 1
fi

if grep -qE '^BYBIT_SANDBOX=true' .env.production; then
  echo "❌ FAIL: .env.production で BYBIT_SANDBOX=true (本番は false 必須)"
  exit 1
fi

if [[ "${FRONTEND_ONLY}" != "true" ]] && grep -qE '^AAVE_NETWORK=.*sepolia' .env.production; then
  echo "❌ FAIL: .env.production で AAVE_NETWORK に sepolia 含む (本番は mainnet 必須)"
  exit 1
elif [[ "${FRONTEND_ONLY}" == "true" ]] && grep -qE '^AAVE_NETWORK=.*sepolia' .env.production; then
  echo "⚠️  WARN: AAVE_NETWORK に sepolia が含まれています (フロントエンドのみデプロイのためスキップ)"
fi

# Guard 2: 環境分離チェック (バックエンドに関わるキーのみ必須 — フロントエンドのみデプロイ時はスキップ)
if [[ "${FRONTEND_ONLY}" == "true" ]]; then
  echo "⚠️  WARN: --frontend-only のため環境分離チェックをスキップ (バックエンド変更なし)"
else
  bash scripts/check_env_separation.sh || {
    echo "❌ FAIL: 環境分離チェック失敗"
    exit 1
  }
fi

# Guard 3: compose file 指定確認
if [[ "${COMPOSE_FILE}" != *production.yml* ]] && [[ -z "${FORCE_OVERRIDE:-}" ]]; then
  echo "❌ FAIL: 本番デプロイは docker-compose.production.yml 必須"
  echo "   (テスター期間の例外で staging.yml を使う場合は FORCE_OVERRIDE=1 を設定)"
  exit 1
fi

echo "✅ All production deploy guards passed"
# === End of guardrails ===

DC=$(resolve_dc)
log "docker compose コマンド: ${DC}"
log "現在の active slot: $(read_active_slot)"

# ───────────────────────────────────────────────
# 共通ステップ 1-4
# ───────────────────────────────────────────────
log "git pull origin main"
git pull origin main

log ".env.production を読み込み（ビルド ARG 用）"
# shellcheck disable=SC2046
export $(grep -v '^#' "${ENV_FILE}" | grep '=' | xargs)

# ───────────────────────────────────────────────
# モード別デプロイ
# ───────────────────────────────────────────────
on_failure() {
  err "デプロイ失敗。コンテナログ末尾:"
  ${DC} -f "${COMPOSE_FILE}" logs --tail=20 2>/dev/null || true
  slack_notify "❌ [deploy_production.sh] デプロイ失敗\n原因: ヘルスチェックタイムアウトまたはビルドエラー"
  exit 1
}
trap on_failure ERR

if "${FRONTEND_ONLY}"; then
  # ─── フロントエンドのみ ───────────────────────
  log "フロントエンドのみデプロイ"

  ${DC} -f "${COMPOSE_FILE}" stop frontend
  docker rm -f "${FRONTEND_CONTAINER}" 2>/dev/null || true

  if ! "${NO_BUILD}"; then
    log "古いフロントエンドイメージを完全削除..."
    docker images --format "{{.Repository}} {{.ID}}" \
      | grep -E "frontend|ultra-autotrade.*front" \
      | awk '{print $2}' \
      | xargs -r docker rmi -f 2>/dev/null || true

    log "frontend をビルド中..."
    ${DC} -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" build --no-cache frontend

    log "古いビルドキャッシュを削除（1時間以上前のエントリ）..."
    docker builder prune --filter until=1h -f 2>/dev/null || true
  fi

  ${DC} -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d frontend

  wait_healthy "http://localhost:3000" "frontend" || on_failure

  log "フロントエンド チャンク数確認..."
  CHUNK_COUNT=$(docker exec "${FRONTEND_CONTAINER}" \
    sh -c "ls /app/.next/static/chunks/ 2>/dev/null | wc -l" || echo "0")
  log "  .next/static/chunks/ ファイル数: ${CHUNK_COUNT}"
  if [ "${CHUNK_COUNT}" -lt 5 ]; then
    log "⚠️  WARNING: チャンク数が少ない（${CHUNK_COUNT}）。ビルドが正常に完了していない可能性があります"
  else
    log "✅ チャンク生成確認 (${CHUNK_COUNT} files)"
  fi

elif "${BACKEND_ONLY}"; then
  # ─── バックエンドのみ (Blue/Green ゼロダウンタイム) ───
  log "バックエンドのみデプロイ (Blue/Green 切替)"

  if ! deploy_backend_zero_downtime; then
    on_failure
  fi

  # nginx 経由のヘルスチェック (cloudflared が見るのと同じ経路)
  wait_healthy "http://localhost:${NGINX_PORT}/health" "nginx → backend (active)" || on_failure

else
  # ─── フルデプロイ ──────────────────────────────
  log "フルデプロイ開始"
  log "初回起動時は active slot=blue で立ち上げ、以降は --backend-only で切替"

  log "📦 Pre-deploy backup..."
  bash "${SCRIPT_DIR}/backup_db.sh" || log "⚠️ Backup failed, continuing deploy..."

  # 既知のフルデプロイは active=blue で再開する。upstream.conf を blue に揃える。
  log "upstream.conf を blue に初期化..."
  write_upstream_conf "blue"

  log "孤立コンテナを含めて停止・削除"
  ${DC} -f "${COMPOSE_FILE}" down --remove-orphans

  # 本番コンテナ (*-production) と移行前の旧 *-staging 残留のみ強制削除。
  # *-staging-new (真の staging 環境) は保護対象なので除外する。
  docker ps -a --format '{{.Names}}' \
    | grep -E '^ultra-autotrade-[a-z-]+-(production|staging)$' \
    | xargs -r docker rm -f 2>/dev/null || true

  log "未使用ボリュームを削除（DBボリュームは名前付きのため保護される）..."
  docker volume prune -f 2>/dev/null || true

  if ! "${NO_BUILD}"; then
    log "古いフロントエンドイメージを完全削除..."
    docker images --format "{{.Repository}} {{.ID}}" \
      | grep -E "frontend|ultra-autotrade.*front" \
      | awk '{print $2}' \
      | xargs -r docker rmi -f 2>/dev/null || true

    log "frontend / backend-blue / backend-green をビルド中（frontend は --no-cache）..."
    ${DC} -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" build --no-cache frontend
    ${DC} -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" build backend-blue backend-green

    log "古いビルドキャッシュを削除（1時間以上前のエントリ）..."
    docker builder prune --filter until=1h -f 2>/dev/null || true
  fi

  log "全サービスを起動 (postgres → backend-blue → nginx → frontend → cloudflared)"
  # 注意: 初回フルデプロイ時は backend-blue のみ起動状態にし、green は手動で起動するまで停止。
  ${DC} -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d
  # green は full deploy 直後は不要なため停止しておく (RAM 節約)
  ${DC} -f "${COMPOSE_FILE}" stop backend-green || true

  wait_healthy "http://127.0.0.1:${BLUE_PORT}/health"     "backend-blue (direct)"   || on_failure
  wait_healthy "http://localhost:${NGINX_PORT}/health"    "nginx → backend"         || on_failure
  wait_healthy "http://localhost:3000"                    "frontend"                || on_failure
fi

# ───────────────────────────────────────────────
# スケジューラー健全性チェック（警告のみ、デプロイは止めない）
# ───────────────────────────────────────────────
if ! "${FRONTEND_ONLY}"; then
  log "15秒待機してスケジューラー状態を確認中..."
  sleep 15
  HEALTH_JSON=$(curl -sf --max-time 5 "http://localhost:${NGINX_PORT}/health" 2>/dev/null || echo '{}')
  SCHED_HEALTHY=$(echo "${HEALTH_JSON}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('scheduler_healthy','unknown'))" 2>/dev/null || echo "unknown")
  if [ "${SCHED_HEALTHY}" = "False" ] || [ "${SCHED_HEALTHY}" = "false" ]; then
    log "⚠️  WARNING: scheduler_healthy=false — スケジューラーが overdue 状態です"
    log "   詳細: ${HEALTH_JSON}"
  elif [ "${SCHED_HEALTHY}" = "unknown" ]; then
    log "⚠️  WARNING: /health からスケジューラー状態を取得できませんでした"
  else
    log "scheduler_healthy=${SCHED_HEALTHY} ✓"
  fi
fi

# ───────────────────────────────────────────────
# デプロイ後 追加検証（WARNING のみ / デプロイは止めない）
# ───────────────────────────────────────────────

# 検証 1: Mixed Content 検出
check_mixed_content() {
  log "=== Mixed Content チェック ==="
  local http_count
  http_count=$(docker exec "${FRONTEND_CONTAINER}" \
    grep -r "http://77\|http://localhost:8000" /app/.next/static/chunks/ 2>/dev/null \
    | wc -l || echo "0")
  if [ "${http_count}" -gt 0 ]; then
    log "⚠️  WARNING: フロントエンドバンドルに http:// URL が ${http_count} 件残っています"
    log "   → NEXT_PUBLIC_* 環境変数が docker-compose build.args に反映されていない可能性"
    log "   → docker compose build --no-cache frontend を実行してください"
  else
    log "✅ Mixed Content なし"
  fi
}

# 検証 2: Cloudflare Tunnel 確認
check_tunnel() {
  log "=== Cloudflare Tunnel チェック ==="
  local named_tunnel
  named_tunnel=$(pgrep -f "cloudflared.*tunnel.*run" 2>/dev/null | wc -l || echo "0")
  if [ "${named_tunnel}" -ge 1 ]; then
    log "✅ Named Tunnel 稼働中 (${named_tunnel} プロセス)"
  else
    local container_running
    container_running=$(docker inspect --format='{{.State.Running}}' \
      "${CLOUDFLARED_CONTAINER}" 2>/dev/null || echo "false")
    if [ "${container_running}" = "true" ]; then
      log "✅ cloudflared コンテナ稼働中"
    else
      log "⚠️  WARNING: Cloudflare Tunnel が検出されませんでした"
      log "   → フロントエンド(:3000) + バックエンド(:${NGINX_PORT}) 両方のトンネルが必要"
      log "   → docker compose logs ${CLOUDFLARED_CONTAINER} で確認してください"
    fi
  fi
}

# 検証 3: DB カラム drift 検出 (active slot のコンテナを参照)
check_db_drift() {
  log "=== DB カラム drift チェック ==="
  local active_container
  active_container=$(active_backend_container)
  log "  active backend container: ${active_container}"
  local db_columns
  db_columns=$(docker exec "${POSTGRES_CONTAINER}" psql -U ultra -d ultra_autotrade -t -c \
    "SELECT string_agg(column_name, ',' ORDER BY ordinal_position) FROM information_schema.columns WHERE table_name='users';" \
    2>/dev/null | tr -d ' \n' || echo "")
  if [ -z "${db_columns}" ]; then
    log "⚠️  WARNING: DB から users テーブルのカラムを取得できませんでした"
    return
  fi
  log "  DB users columns: ${db_columns}"
  local model_columns
  model_columns=$(docker exec "${active_container}" python -c \
    "from app.auth.models import User; cols=[c.key for c in User.__table__.columns]; print(','.join(sorted(cols)))" \
    2>/dev/null || echo "")
  if [ -z "${model_columns}" ]; then
    log "⚠️  WARNING: モデルからカラムを取得できませんでした"
    return
  fi
  log "  Model columns: ${model_columns}"
  local diff
  diff=$(comm -23 \
    <(echo "${model_columns}" | tr ',' '\n' | sort) \
    <(echo "${db_columns}" | tr ',' '\n' | sort) || true)
  if [ -n "${diff}" ]; then
    log "⚠️  WARNING: 以下のカラムがモデルにあるが DB にありません:"
    log "   ${diff}"
    log "   → ALTER TABLE users ADD COLUMN IF NOT EXISTS ... で追加してください"
  else
    log "✅ DB カラム drift なし"
  fi
}

# 検証 4: 401 エラー確認（INTERNAL_API_TOKEN 問題検出）
check_auth_errors() {
  log "=== 内部 API 認証エラーチェック ==="
  local active_container
  active_container=$(active_backend_container)
  local auth_errors
  auth_errors=$(docker logs "${active_container}" 2>&1 | tail -100 \
    | grep -c "401 Unauthorized" || echo "0")
  if [ "${auth_errors}" -gt 5 ]; then
    log "⚠️  WARNING: 直近100行に 401 Unauthorized が ${auth_errors} 件 (${active_container})"
    log "   → INTERNAL_API_TOKEN が .env.production に設定されているか確認してください"
  else
    log "✅ 401 エラー ${auth_errors} 件（正常範囲）"
  fi
}

# 検証 5: CORS preflight 自動検証
check_cors() {
  log "=== CORS preflight チェック ==="
  local frontend_origin="${CORS_ORIGINS:-https://app.ultra-auto-trade.com}"
  frontend_origin="${frontend_origin%%,*}"  # 最初のオリジンのみ使用
  local cors_header
  cors_header=$(curl -s -I \
    -H "Origin: ${frontend_origin}" \
    -H "Access-Control-Request-Method: GET" \
    --max-time 5 \
    "http://localhost:${NGINX_PORT}/health" 2>/dev/null \
    | grep -i "access-control-allow-origin" | tr -d '\r' || echo "")
  if echo "${cors_header}" | grep -q "${frontend_origin}\|\*"; then
    log "✅ CORS: ${frontend_origin} が許可されています"
  else
    log "⚠️  WARNING: CORS ヘッダーに ${frontend_origin} が含まれていません"
    log "   → .env.production の CORS_ORIGINS に ${frontend_origin} を追加してください"
    log "   → レスポンス: ${cors_header:-（ヘッダーなし）}"
  fi
}

# 検証 6: nginx upstream 整合性 (active slot と nginx upstream の一致確認)
check_nginx_upstream() {
  log "=== nginx upstream 整合性チェック ==="
  local active_slot
  active_slot=$(read_active_slot)
  if [ "${active_slot}" = "unknown" ]; then
    log "⚠️  WARNING: upstream.conf から active slot を判定できません"
    return
  fi
  log "  upstream.conf active slot: ${active_slot}"
  local nginx_running
  nginx_running=$(docker inspect --format='{{.State.Running}}' "${NGINX_CONTAINER}" 2>/dev/null || echo "false")
  if [ "${nginx_running}" != "true" ]; then
    log "⚠️  WARNING: nginx コンテナが稼働していません (${NGINX_CONTAINER})"
    return
  fi
  # nginx 経由でアクセスして応答を確認
  if curl -sf --max-time 3 "http://localhost:${NGINX_PORT}/nginx-health" >/dev/null 2>&1; then
    log "✅ nginx ${NGINX_PORT} → backend-${active_slot} 疎通 OK"
  else
    log "⚠️  WARNING: nginx ${NGINX_PORT} に到達できません"
  fi
}

# 全追加検証を実行（各ステップは独立して動作）
run_post_deploy_checks() {
  log "=== デプロイ後追加検証 開始 ==="
  check_mixed_content   || true
  check_tunnel          || true
  check_db_drift        || true
  check_auth_errors     || true
  check_cors            || true
  check_nginx_upstream  || true
  log "=== デプロイ後追加検証 完了 ==="
}

if ! "${BACKEND_ONLY}"; then
  run_post_deploy_checks
else
  # backend-only でも nginx upstream 整合性は確認したい
  check_nginx_upstream || true
fi

# ───────────────────────────────────────────────
# 最終ヘルスチェック（HTTP ステータス確認）
# ───────────────────────────────────────────────
log "=== 最終ヘルスチェック ==="

# バックエンド (nginx 経由)
if ! "${FRONTEND_ONLY}"; then
  BE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 "http://localhost:${NGINX_PORT}/health" 2>/dev/null || echo "000")
  if [ "${BE_STATUS}" = "200" ]; then
    log "✅ backend  http://localhost:${NGINX_PORT}/health → ${BE_STATUS} (active=$(read_active_slot))"
  else
    log "⚠️  WARNING: backend  http://localhost:${NGINX_PORT}/health → ${BE_STATUS}"
  fi
fi

# フロントエンド
if ! "${BACKEND_ONLY}"; then
  FE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 http://localhost:3000 2>/dev/null || echo "000")
  if [ "${FE_STATUS}" = "200" ]; then
    log "✅ frontend http://localhost:3000 → ${FE_STATUS}"
  else
    log "⚠️  WARNING: frontend http://localhost:3000 → ${FE_STATUS} (リダイレクトや初期化中の可能性あり)"
  fi
fi

log "=== 最終ヘルスチェック 完了 ==="

# ───────────────────────────────────────────────
# 完了報告
# ───────────────────────────────────────────────
log "コンテナ状態:"
${DC} -f "${COMPOSE_FILE}" ps

slack_notify "✅ [deploy_production.sh] デプロイ成功\n環境: production\nactive slot: $(read_active_slot)\nブランチ: $(git rev-parse --abbrev-ref HEAD) ($(git rev-parse --short HEAD))"

log "デプロイ完了 (active slot: $(read_active_slot))"
