#!/usr/bin/env python3
# scripts/generate_test_wallet.py

"""
テスト用ウォレット生成スクリプト。

Web3.py を使用して新規ウォレットを生成し、
Mumbai テストネット用の環境変数を出力する。

Usage:
    python scripts/generate_test_wallet.py
    python scripts/generate_test_wallet.py --output backend/.env.test
    python scripts/generate_test_wallet.py --json

Security:
    - このスクリプトで生成されるウォレットはテスト専用
    - 秘密鍵は絶対に本番環境で使用しない
    - 秘密鍵は絶対にコミットしない
"""

from __future__ import annotations

import argparse
import json
import secrets
import sys
from pathlib import Path

# Fail-fast: eth-account が必須
try:
    from eth_account import Account
except ImportError:
    print("ERROR: eth-account is not installed", file=sys.stderr)
    print("Please run: pip install eth-account", file=sys.stderr)
    print("", file=sys.stderr)
    print("Note: eth-account is listed in backend/requirements.txt", file=sys.stderr)
    print("      Run: pip install -r backend/requirements.txt", file=sys.stderr)
    sys.exit(1)


def generate_wallet() -> tuple[str, str]:
    """
    新規ウォレットを生成する。

    Returns:
        tuple[str, str]: (アドレス, 秘密鍵)
    """
    # ランダムな秘密鍵を生成
    private_key = "0x" + secrets.token_hex(32)
    account = Account.from_key(private_key)

    return account.address, private_key


def print_security_warning() -> None:
    """セキュリティ警告を表示する。"""
    warning = """
╔══════════════════════════════════════════════════════════════════════╗
║                        ⚠️  セキュリティ警告  ⚠️                         ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                      ║
║  このウォレットはテスト専用です                                      ║
║                                                                      ║
║  ❌ 本番環境では絶対に使用しないでください                           ║
║  ❌ 秘密鍵を絶対にコミットしないでください                           ║
║  ❌ 秘密鍵を他人と共有しないでください                               ║
║  ❌ 実際の資金をこのウォレットに送らないでください                   ║
║                                                                      ║
║  ✅ テストネット（Mumbai）でのみ使用してください                     ║
║  ✅ 秘密鍵は安全な場所に保管してください                             ║
║  ✅ .env.test は .gitignore に含まれていることを確認してください     ║
║                                                                      ║
╚══════════════════════════════════════════════════════════════════════╝
"""
    print(warning)


def print_wallet_info(address: str, private_key: str) -> None:
    """ウォレット情報を表示する。"""
    print("\n📋 生成されたウォレット情報:")
    print("=" * 60)
    print(f"ウォレットアドレス: {address}")
    print(f"秘密鍵:             {private_key}")
    print("=" * 60)


def print_next_steps(address: str) -> None:
    """次のステップを表示する。"""
    print("\n📌 次のステップ:")
    print("-" * 60)
    print("1. Mumbai MATIC を取得（ガス代用）:")
    print("   https://faucet.polygon.technology/")
    print()
    print("2. Test USDC を取得（Aave テスト用）:")
    print("   https://app.aave.com/faucet/")
    print()
    print("3. ウォレット残高を確認:")
    print(f"   https://mumbai.polygonscan.com/address/{address}")
    print()
    print("4. .env.test を作成して環境変数を設定:")
    print("   cp backend/.env.test.example backend/.env.test")
    print("   # 秘密鍵を .env.test に追記")
    print()
    print("5. E2E テストを実行:")
    print("   RUN_E2E_TESTS=1 pytest backend/tests/ -m e2e -v")
    print("-" * 60)


def generate_env_content(address: str, private_key: str) -> str:
    """環境変数ファイルの内容を生成する。"""
    return f"""# ================================================
# Mumbai E2E Test Environment Variables
# ================================================
# ⚠️  このファイルは .gitignore に含まれています
# ⚠️  絶対にコミットしないでください
# ================================================

# Wallet Configuration (Generated by generate_test_wallet.py)
AAVE_WALLET_ADDRESS={address}
AAVE_WALLET_PRIVATE_KEY={private_key}

# Mumbai RPC (Alchemy/Infura/public)
# 公開 RPC: https://rpc-mumbai.maticvigil.com
# Alchemy: https://polygon-mumbai.g.alchemy.com/v2/YOUR_API_KEY
AAVE_RPC_URL=https://rpc-mumbai.maticvigil.com

# Aave V3 Pool Address (Mumbai Testnet)
AAVE_POOL_ADDRESS=0x0b913A76beFF3887d35073b8e5530755D60F78C7

# Pool Addresses Provider (Mumbai Testnet)
AAVE_POOL_ADDRESSES_PROVIDER=0x5343b5bA672Ae99d627A1C87866b8E53F47Db2E6

# Test USDC Address (Mumbai Testnet)
AAVE_USDC_ADDRESS=0x52D800ca262522580CeBAD275395ca6e7598C014

# Chain ID (Mumbai = 80001)
AAVE_CHAIN_ID=80001

# E2E Test Flag
RUN_E2E_TESTS=1

# Client Type
AAVE_CLIENT_TYPE=web3
"""


def write_env_file(output_path: Path, address: str, private_key: str) -> None:
    """環境変数ファイルを書き込む。"""
    content = generate_env_content(address, private_key)

    with open(output_path, "w") as f:
        f.write(content)

    print(f"\n✅ 環境変数ファイルを生成しました: {output_path}")


def main() -> None:
    """メインエントリーポイント。"""
    parser = argparse.ArgumentParser(
        description="テスト用ウォレットを生成する",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # 基本的な使用法
    python scripts/generate_test_wallet.py

    # .env.test に出力
    python scripts/generate_test_wallet.py --output backend/.env.test

    # JSON 形式で出力
    python scripts/generate_test_wallet.py --json

Security:
    生成されたウォレットはテスト専用です。
    本番環境では絶対に使用しないでください。
""",
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        help="環境変数ファイルの出力先パス",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="JSON 形式で出力",
    )
    parser.add_argument(
        "--quiet", "-q",
        action="store_true",
        help="警告メッセージを抑制",
    )

    args = parser.parse_args()

    # ウォレット生成
    address, private_key = generate_wallet()

    if args.json:
        # JSON 形式で出力
        output = {
            "address": address,
            "private_key": private_key,
            "chain_id": 80001,
            "network": "mumbai",
            "warning": "THIS WALLET IS FOR TESTING ONLY. DO NOT USE IN PRODUCTION.",
        }
        print(json.dumps(output, indent=2))
        return

    # 通常の出力
    if not args.quiet:
        print_security_warning()

    print_wallet_info(address, private_key)

    if args.output:
        write_env_file(args.output, address, private_key)

    if not args.quiet:
        print_next_steps(address)


if __name__ == "__main__":
    main()
